disabled_rules:
 - line_length
 - force_cast
 - force_try

file_length:
  warning: 160
  error: 160

cyclomatic_complexity:
  warning: 5
  error: 5

function_body_length:
  warning: 15
  error: 15

function_parameter_count:
  warning: 5
  error: 5

excluded:
  - Carthage
